services:

  # ElasticSearch Content

  # elasticsearch_kibana:
  #   image: docker.elastic.co/kibana/kibana:8.11.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    # deploy:
    #   mode: replicated
    #   replicas: 3  # Three Elasticsearch nodes for clustering
    #   resources:
    #     limits:
    #       memory: 2G
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app_network

volumes:
  elasticsearch_data:

networks:
  app_network:
    driver: bridge

