services:

  # Neo4j Stack

  # neo4j_browser:
  #   image: neo4j:5.13
  #   environment:
  #     - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
  #   ports:
  #     - "7474:7474"  # Neo4j Browser UI
  #     - "7687:7687"  # Bolt protocol
  #   depends_on:
  #     - neo4j

  neo4j:
    image: neo4j:5.13
    # deploy:
    #   mode: replicated
    #   replicas: 2
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1024M
    ports:
      - "7474:7474"  # Browser UI
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
    networks:
      - app_network

volumes:
  neo4j_data:

networks:
  app_network:
    driver: bridge

