services:
  
  # Redis Content

  redis_insight:
    image: redis/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    deploy:
      mode: global
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app_network

volumes:
  redis_data:
  redisinsight_data:

networks:
  app_network:
    driver: bridge
